[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio-macros = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
serde = { version = "1.0.208", features = ["derive"] }
config = "0.14"

[dependencies.sqlx]
version = "0.8"
default-features = false
features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"]

[dev-dependencies]
reqwest = "0.12"
