[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio-macros = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }

[dev-dependencies]
reqwest = "0.12.6"
