application:
  app_port: 8000
  signing_key: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  username: postgres
  password: password
  port: 5432
  database: newsletter
email_client:
  timeout_millis: 10000
